export const UKUniversities = [
  'Aberystwyth University',
  'Anglia Ruskin University',
  'Aston University',
  'Bangor University',
  'Bath Spa University',
  'Birkbeck, University of London',
  'Birmingham City University',
  'Bishop Grosseteste University',
  'Bournemouth University',
  'Brunel University London',
  'Buckinghamshire New University',
  'Canterbury Christ Church University',
  'Cardiff Metropolitan University',
  'Cardiff University',
  'City, University of London',
  'Coventry University',
  'Cranfield University',
  'De Montfort University',
  'Durham University',
  'Edge Hill University',
  'Edinburgh Napier University',
  'Glasgow Caledonian University',
  'Goldsmiths, University of London',
  'Harper Adams University',
  'Heriot-Watt University',
  'Imperial College London',
  'Keele University',
  "King's College London",
  'Kingston University',
  'Lancaster University',
  'Leeds Arts University',
  'Leeds Beckett University',
  'Leeds Trinity University',
  'Liverpool Hope University',
  'Liverpool John Moores University',
  'London Metropolitan University',
  'London School of Economics and Political Science',
  'London South Bank University',
  'Loughborough University',
  'Manchester Metropolitan University',
  'Middlesex University',
  'Newcastle University',
  'Northumbria University',
  'Norwich University of the Arts',
  'Nottingham Trent University',
  'Open University',
  'Oxford Brookes University',
  'Plymouth Marjon University',
  'Queen Margaret University, Edinburgh',
  'Queen Mary University of London',
  "Queen's University Belfast",
  'Ravensbourne University London',
];
